/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ChronicleRegistry {
  export type WatchCampaignStruct = {
    targetContract: AddressLike;
    watchSpecHash: BytesLike;
    startsAt: BigNumberish;
    endsAt: BigNumberish;
    createdAt: BigNumberish;
    reportUri: string;
    reportContentHash: BytesLike;
    sourceEventRoot: BytesLike;
  };

  export type WatchCampaignStructOutput = [
    targetContract: string,
    watchSpecHash: string,
    startsAt: bigint,
    endsAt: bigint,
    createdAt: bigint,
    reportUri: string,
    reportContentHash: string,
    sourceEventRoot: string
  ] & {
    targetContract: string;
    watchSpecHash: string;
    startsAt: bigint;
    endsAt: bigint;
    createdAt: bigint;
    reportUri: string;
    reportContentHash: string;
    sourceEventRoot: string;
  };
}

export interface ChronicleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "alerts"
      | "createSponsoredWatch"
      | "digests"
      | "getAlertTimestamp"
      | "getDigestTimestamp"
      | "getPayoutTimestamp"
      | "getWatch"
      | "nextWatchId"
      | "owner"
      | "payouts"
      | "publishAlert"
      | "publishDigest"
      | "publishSponsoredReport"
      | "recordPayout"
      | "sponsoredWatches"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AlertPublished"
      | "DigestPublished"
      | "PayoutRecorded"
      | "SponsoredReportPublished"
      | "SponsoredWatchCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "alerts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "createSponsoredWatch",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "digests", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAlertTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDigestTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayoutTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextWatchId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "payouts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "publishAlert",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "publishDigest",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "publishSponsoredReport",
    values: [BigNumberish, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPayout",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsoredWatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "alerts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createSponsoredWatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "digests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAlertTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDigestTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayoutTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextWatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payouts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishAlert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishSponsoredReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sponsoredWatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AlertPublishedEvent {
  export type InputTuple = [
    alertHash: BytesLike,
    ipfsUri: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    alertHash: string,
    ipfsUri: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    alertHash: string;
    ipfsUri: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DigestPublishedEvent {
  export type InputTuple = [
    digestHash: BytesLike,
    sourceEventRoot: BytesLike,
    ipfsUri: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    digestHash: string,
    sourceEventRoot: string,
    ipfsUri: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    digestHash: string;
    sourceEventRoot: string;
    ipfsUri: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutRecordedEvent {
  export type InputTuple = [
    payoutPeriodHash: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    reasonHash: BytesLike
  ];
  export type OutputTuple = [
    payoutPeriodHash: string,
    recipient: string,
    amount: bigint,
    reasonHash: string
  ];
  export interface OutputObject {
    payoutPeriodHash: string;
    recipient: string;
    amount: bigint;
    reasonHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsoredReportPublishedEvent {
  export type InputTuple = [
    watchId: BigNumberish,
    reportContentHash: BytesLike,
    sourceEventRoot: BytesLike,
    reportUri: string
  ];
  export type OutputTuple = [
    watchId: bigint,
    reportContentHash: string,
    sourceEventRoot: string,
    reportUri: string
  ];
  export interface OutputObject {
    watchId: bigint;
    reportContentHash: string;
    sourceEventRoot: string;
    reportUri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsoredWatchCreatedEvent {
  export type InputTuple = [
    watchId: BigNumberish,
    targetContract: AddressLike,
    watchSpecHash: BytesLike,
    startsAt: BigNumberish,
    endsAt: BigNumberish
  ];
  export type OutputTuple = [
    watchId: bigint,
    targetContract: string,
    watchSpecHash: string,
    startsAt: bigint,
    endsAt: bigint
  ];
  export interface OutputObject {
    watchId: bigint;
    targetContract: string;
    watchSpecHash: string;
    startsAt: bigint;
    endsAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChronicleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ChronicleRegistry;
  waitForDeployment(): Promise<this>;

  interface: ChronicleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  alerts: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  createSponsoredWatch: TypedContractMethod<
    [
      targetContract: AddressLike,
      watchSpecHash: BytesLike,
      startsAt: BigNumberish,
      endsAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  digests: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getAlertTimestamp: TypedContractMethod<
    [alertHash: BytesLike],
    [bigint],
    "view"
  >;

  getDigestTimestamp: TypedContractMethod<
    [digestHash: BytesLike],
    [bigint],
    "view"
  >;

  getPayoutTimestamp: TypedContractMethod<
    [payoutPeriodHash: BytesLike],
    [bigint],
    "view"
  >;

  getWatch: TypedContractMethod<
    [watchId: BigNumberish],
    [ChronicleRegistry.WatchCampaignStructOutput],
    "view"
  >;

  nextWatchId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payouts: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  publishAlert: TypedContractMethod<
    [alertHash: BytesLike, ipfsUri: string],
    [void],
    "nonpayable"
  >;

  publishDigest: TypedContractMethod<
    [digestHash: BytesLike, sourceEventRoot: BytesLike, ipfsUri: string],
    [void],
    "nonpayable"
  >;

  publishSponsoredReport: TypedContractMethod<
    [
      watchId: BigNumberish,
      reportContentHash: BytesLike,
      sourceEventRoot: BytesLike,
      reportUri: string
    ],
    [void],
    "nonpayable"
  >;

  recordPayout: TypedContractMethod<
    [
      payoutPeriodHash: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reasonHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  sponsoredWatches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, string, string] & {
        targetContract: string;
        watchSpecHash: string;
        startsAt: bigint;
        endsAt: bigint;
        createdAt: bigint;
        reportUri: string;
        reportContentHash: string;
        sourceEventRoot: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "alerts"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createSponsoredWatch"
  ): TypedContractMethod<
    [
      targetContract: AddressLike,
      watchSpecHash: BytesLike,
      startsAt: BigNumberish,
      endsAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "digests"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAlertTimestamp"
  ): TypedContractMethod<[alertHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDigestTimestamp"
  ): TypedContractMethod<[digestHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayoutTimestamp"
  ): TypedContractMethod<[payoutPeriodHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWatch"
  ): TypedContractMethod<
    [watchId: BigNumberish],
    [ChronicleRegistry.WatchCampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextWatchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payouts"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "publishAlert"
  ): TypedContractMethod<
    [alertHash: BytesLike, ipfsUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publishDigest"
  ): TypedContractMethod<
    [digestHash: BytesLike, sourceEventRoot: BytesLike, ipfsUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publishSponsoredReport"
  ): TypedContractMethod<
    [
      watchId: BigNumberish,
      reportContentHash: BytesLike,
      sourceEventRoot: BytesLike,
      reportUri: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPayout"
  ): TypedContractMethod<
    [
      payoutPeriodHash: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reasonHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sponsoredWatches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, string, string] & {
        targetContract: string;
        watchSpecHash: string;
        startsAt: bigint;
        endsAt: bigint;
        createdAt: bigint;
        reportUri: string;
        reportContentHash: string;
        sourceEventRoot: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AlertPublished"
  ): TypedContractEvent<
    AlertPublishedEvent.InputTuple,
    AlertPublishedEvent.OutputTuple,
    AlertPublishedEvent.OutputObject
  >;
  getEvent(
    key: "DigestPublished"
  ): TypedContractEvent<
    DigestPublishedEvent.InputTuple,
    DigestPublishedEvent.OutputTuple,
    DigestPublishedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutRecorded"
  ): TypedContractEvent<
    PayoutRecordedEvent.InputTuple,
    PayoutRecordedEvent.OutputTuple,
    PayoutRecordedEvent.OutputObject
  >;
  getEvent(
    key: "SponsoredReportPublished"
  ): TypedContractEvent<
    SponsoredReportPublishedEvent.InputTuple,
    SponsoredReportPublishedEvent.OutputTuple,
    SponsoredReportPublishedEvent.OutputObject
  >;
  getEvent(
    key: "SponsoredWatchCreated"
  ): TypedContractEvent<
    SponsoredWatchCreatedEvent.InputTuple,
    SponsoredWatchCreatedEvent.OutputTuple,
    SponsoredWatchCreatedEvent.OutputObject
  >;

  filters: {
    "AlertPublished(bytes32,string,uint256)": TypedContractEvent<
      AlertPublishedEvent.InputTuple,
      AlertPublishedEvent.OutputTuple,
      AlertPublishedEvent.OutputObject
    >;
    AlertPublished: TypedContractEvent<
      AlertPublishedEvent.InputTuple,
      AlertPublishedEvent.OutputTuple,
      AlertPublishedEvent.OutputObject
    >;

    "DigestPublished(bytes32,bytes32,string,uint256)": TypedContractEvent<
      DigestPublishedEvent.InputTuple,
      DigestPublishedEvent.OutputTuple,
      DigestPublishedEvent.OutputObject
    >;
    DigestPublished: TypedContractEvent<
      DigestPublishedEvent.InputTuple,
      DigestPublishedEvent.OutputTuple,
      DigestPublishedEvent.OutputObject
    >;

    "PayoutRecorded(bytes32,address,uint256,bytes32)": TypedContractEvent<
      PayoutRecordedEvent.InputTuple,
      PayoutRecordedEvent.OutputTuple,
      PayoutRecordedEvent.OutputObject
    >;
    PayoutRecorded: TypedContractEvent<
      PayoutRecordedEvent.InputTuple,
      PayoutRecordedEvent.OutputTuple,
      PayoutRecordedEvent.OutputObject
    >;

    "SponsoredReportPublished(uint256,bytes32,bytes32,string)": TypedContractEvent<
      SponsoredReportPublishedEvent.InputTuple,
      SponsoredReportPublishedEvent.OutputTuple,
      SponsoredReportPublishedEvent.OutputObject
    >;
    SponsoredReportPublished: TypedContractEvent<
      SponsoredReportPublishedEvent.InputTuple,
      SponsoredReportPublishedEvent.OutputTuple,
      SponsoredReportPublishedEvent.OutputObject
    >;

    "SponsoredWatchCreated(uint256,address,bytes32,uint256,uint256)": TypedContractEvent<
      SponsoredWatchCreatedEvent.InputTuple,
      SponsoredWatchCreatedEvent.OutputTuple,
      SponsoredWatchCreatedEvent.OutputObject
    >;
    SponsoredWatchCreated: TypedContractEvent<
      SponsoredWatchCreatedEvent.InputTuple,
      SponsoredWatchCreatedEvent.OutputTuple,
      SponsoredWatchCreatedEvent.OutputObject
    >;
  };
}
