import type { ReactElement } from "react";
import { Link } from "react-router-dom";
import { StatusBadge, TimestampDisplay } from "../../components/data-primitives.tsx";
import {
  MetaChip,
  Page,
  PageHeader,
  Surface,
} from "../../components/page-chrome.tsx";
import { EmptyState, LoadingState, RetryState } from "../../components/state-views.tsx";
import { useAgentActivity } from "../activity/use-agent-activity.ts";
import { useAlerts } from "../alerts/use-alerts.ts";
import { usePremiumTeasers } from "../premium/use-premium.ts";

interface PublicationItem {
  id: string;
  type: "digest" | "alert" | "premium";
  title: string;
  summary: string;
  date: string;
  status: string;
  href: string;
  meta: Record<string, string>;
}

const TYPE_STYLES: Record<
  PublicationItem["type"],
  { label: string; className: string }
> = {
  digest: {
    label: "Digest",
    className: "bg-accent/15 text-foreground border-accent/30",
  },
  alert: {
    label: "Alert",
    className: "bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/25",
  },
  premium: {
    label: "Premium",
    className: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/25",
  },
};

export function PublicationsPage(): ReactElement {
  const { alerts, isLoading: alertsLoading, error: alertsError, refetch: refetchAlerts } =
    useAlerts(100);
  const {
    data: activity,
    isLoading: activityLoading,
    error: activityError,
    refetch: refetchActivity,
  } = useAgentActivity();
  const {
    items: premiumItems,
    isLoading: premiumLoading,
    error: premiumError,
    refetch: refetchPremium,
  } = usePremiumTeasers();

  const publications: PublicationItem[] = [];

  for (const digest of activity?.digests ?? []) {
    publications.push({
      id: digest.id,
      type: "digest",
      title: digest.title,
      summary: digest.summary.slice(0, 200),
      date: digest.publishedAt ?? digest.reportDate,
      status: digest.publicationStatus,
      href: `/digests/${digest.id}`,
      meta: {
        ...(digest.registryTxHash ? { "Registry Tx": digest.registryTxHash } : {}),
        ...(digest.keeperHubRunId ? { "KeeperHub run": digest.keeperHubRunId } : {}),
      },
    });
  }

  for (const alert of alerts) {
    publications.push({
      id: alert.id,
      type: "alert",
      title: alert.title,
      summary: alert.summary,
      date: alert.publishedAt ?? "",
      status: alert.deliveryStatus,
      href: `/alerts/${alert.id}`,
      meta: {
        ...(alert.generationProvider ? { "Generated by": alert.generationProvider } : {}),
        ...(alert.confidence ? { Confidence: alert.confidence } : {}),
        ...(alert.eventType ? { Event: alert.eventType.replace(/_/g, " ") } : {}),
        ...(typeof alert.chainId === "number" ? { Chain: String(alert.chainId) } : {}),
      },
    });
  }

  for (const item of premiumItems) {
    publications.push({
      id: item.id,
      type: "premium",
      title: item.title,
      summary: item.summaryPublic,
      date: "",
      status: "available",
      href: "/premium",
      meta: {
        Price: `${item.priceAmount} ${item.priceCurrency}`,
      },
    });
  }

  publications.sort((a, b) => {
    if (!a.date && !b.date) return 0;
    if (!a.date) return 1;
    if (!b.date) return -1;
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });

  const isLoading = alertsLoading || activityLoading || premiumLoading;
  const hasError = alertsError || activityError || premiumError;

  const refetchAll = () => {
    refetchAlerts();
    refetchActivity();
    refetchPremium();
  };

  return (
    <Page data-testid="publications-page">
      <PageHeader
        title="Publications Archive"
        description="The complete archive of ChronicleAI intelligence — public alerts, digests, and premium analysis."
        meta={
          !isLoading && !hasError ? (
            <span>
              {publications.length} item{publications.length !== 1 ? "s" : ""}
            </span>
          ) : undefined
        }
      />

      {isLoading ? (
        <LoadingState message="Loading publications..." variant="cards" count={5} />
      ) : hasError ? (
        <RetryState
          title="Failed to load publications"
          message={alertsError ?? activityError ?? premiumError ?? "Unknown error"}
          onRetry={refetchAll}
        />
      ) : publications.length === 0 ? (
        <EmptyState
          title="No publications yet"
          description="ChronicleAI content will appear here once alerts, digests, and premium items are published."
        />
      ) : (
        <div className="flex flex-col gap-4">
          {publications.map((pub) => {
            const typeStyle = TYPE_STYLES[pub.type];
            return (
              <Surface
                as="article"
                key={`${pub.type}-${pub.id}`}
                className="p-5 hover:border-accent/40 transition-colors duration-200"
              >
                <div className="flex justify-between items-center mb-3 flex-wrap gap-2">
                  <span
                    className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold border ${typeStyle.className}`}
                  >
                    {typeStyle.label}
                  </span>
                  <div className="flex items-center gap-3">
                    {pub.date ? <TimestampDisplay timestamp={pub.date} /> : null}
                    {pub.status !== "available" ? (
                      <StatusBadge
                        label={pub.status}
                        variant={
                          pub.status === "published"
                            ? "success"
                            : pub.status === "partial_failure"
                              ? "warning"
                              : "default"
                        }
                      />
                    ) : null}
                  </div>
                </div>

                <h3 className="text-lg font-semibold text-foreground mb-2 leading-snug">
                  {pub.title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed mb-4">
                  {pub.summary}
                </p>

                <div className="flex justify-between items-center flex-wrap gap-3 pt-4 border-t border-border/40">
                  <div className="flex flex-wrap gap-2">
                    {Object.entries(pub.meta).map(([key, value]) => (
                      <MetaChip key={key}>
                        {key}: {value.length > 30 ? `${value.slice(0, 16)}…` : value}
                      </MetaChip>
                    ))}
                  </div>
                  <Link
                    to={pub.href}
                    className="text-xs font-semibold text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Read more →
                  </Link>
                </div>
              </Surface>
            );
          })}
        </div>
      )}
    </Page>
  );
}
