// Publications page — the ChronicleAI newspaper hub showing all published content

import type { ReactElement } from "react";
import { Link } from "react-router-dom";
import { EmptyState, LoadingState, RetryState } from "../../components/state-views.tsx";
import { StatusBadge, TimestampDisplay } from "../../components/data-primitives.tsx";
import { useAlerts } from "../alerts/use-alerts.ts";
import { useLatestDigest } from "../digests/use-latest-digest.ts";
import { usePremiumTeasers } from "../premium/use-premium.ts";

interface PublicationItem {
  id: string;
  type: "digest" | "alert" | "premium";
  title: string;
  summary: string;
  date: string;
  status: string;
  href: string;
  meta: Record<string, string>;
}

export function PublicationsPage(): ReactElement {
  const { alerts, isLoading: alertsLoading, error: alertsError, refetch: refetchAlerts } = useAlerts(100);
  const { state: digestState } = useLatestDigest();
  const { items: premiumItems, isLoading: premiumLoading } = usePremiumTeasers();

  // Build a unified publication feed
  const publications: PublicationItem[] = [];

  if (digestState.status === "success") {
    publications.push({
      id: digestState.data.id,
      type: "digest",
      title: digestState.data.title,
      summary: digestState.data.summary.slice(0, 200),
      date: digestState.data.publishedAt ?? digestState.data.reportDate,
      status: digestState.data.publicationStatus,
      href: "/digests/latest",
      meta: {
        ...(digestState.data.registryTxHash ? { "Registry Tx": digestState.data.registryTxHash } : {}),
      },
    });
  }

  for (const alert of alerts) {
    publications.push({
      id: alert.id,
      type: "alert",
      title: alert.title,
      summary: alert.summary,
      date: alert.publishedAt ?? new Date().toISOString(),
      status: alert.deliveryStatus,
      href: "/alerts",
      meta: {
        ...(alert.generationProvider ? { "Generated by": alert.generationProvider } : {}),
        ...(alert.confidence ? { Confidence: alert.confidence } : {}),
      },
    });
  }

  for (const item of premiumItems) {
    publications.push({
      id: item.id,
      type: "premium",
      title: item.title,
      summary: item.summaryPublic,
      date: "",
      status: "available",
      href: "/premium",
      meta: {
        Price: `${item.priceAmount} ${item.priceCurrency}`,
      },
    });
  }

  // Sort by date descending (most recent first)
  publications.sort((a, b) => {
    if (!a.date && !b.date) return 0;
    if (!a.date) return 1;
    if (!b.date) return -1;
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });

  const isLoading = alertsLoading || digestState.status === "loading" || premiumLoading;
  const hasError = alertsError || digestState.status === "error";

  return (
    <div className="newspaper-layout">
      {/* ── Publications Masthead ──────────────────────── */}

      <header className="newspaper-masthead">
        <div className="masthead-accent-line" />
        <h1 className="masthead-title" style={{ fontSize: "var(--font-size-3xl)" }}>
          Publications
        </h1>
        <p className="masthead-subtitle">
          The complete archive of ChronicleAI intelligence &mdash; alerts, reports, and premium analysis
        </p>
        <div className="masthead-accent-line" />
      </header>

      {/* ── Section Navigation ──────────────────────── */}
      <nav className="publications-filter-nav">
        <span className="publications-filter-label">Sections:</span>
        <span className="publications-filter-label-current">All Publications</span>
        <Link to="/digests/latest" className="publications-filter-btn">Digest</Link>
        <Link to="/alerts" className="publications-filter-btn">Alerts</Link>
        <Link to="/premium" className="publications-filter-btn">Premium</Link>
      </nav>

      {/* ── Publication Feed ──────────────────────────── */}
      <section className="publications-feed">
        {isLoading ? (
          <LoadingState message="Loading publications..." />
        ) : hasError ? (
          <RetryState title="Failed to load publications" message={alertsError ?? "Unknown error"} onRetry={refetchAlerts} />
        ) : publications.length === 0 ? (
          <EmptyState
            title="No publications yet"
            description="ChronicleAI content will appear here once alerts, digests, and premium items are published."
          />
        ) : (
          <div className="publications-timeline">
            {/* Date group headers */}
            {publications.map((pub) => {
              const typeColor = pub.type === "digest" ? "var(--accent-primary)" : pub.type === "alert" ? "var(--accent-warning)" : "var(--accent-success)";

              return (
                <article key={`${pub.type}-${pub.id}`} className="publication-item">
                  <div className="publication-item-timeline">
                    <div className="publication-timeline-dot" style={{ background: typeColor }} />
                    <div className="publication-timeline-line" />
                  </div>
                  <div className="publication-item-card">
                    <div className="publication-item-header">
                      <span className="publication-item-type" style={{ color: typeColor }}>
                        <span className="publication-type-indicator" style={{ background: typeColor }} />
                        {pub.type.charAt(0).toUpperCase() + pub.type.slice(1)}
                      </span>
                      <div className="publication-item-meta-top">
                        {pub.date && <TimestampDisplay timestamp={pub.date} />}
                        {pub.status !== "available" && (
                          <StatusBadge label={pub.status} variant={pub.status === "published" ? "success" : pub.status === "partial_failure" ? "warning" : "default"} />
                        )}
                      </div>
                    </div>
                    <h3 className="publication-item-title">{pub.title}</h3>
                    <p className="publication-item-summary">{pub.summary}</p>
                    <div className="publication-item-footer">
                      <div className="publication-item-meta">
                        {Object.entries(pub.meta).map(([key, value]) => (
                          <span key={key} className="publication-meta-tag">
                            {key}: {value.length > 30 ? `${value.slice(0, 16)}...` : value}
                          </span>
                        ))}
                      </div>
                      <Link to={pub.href} className="publication-item-link">
                        Read More &rarr;
                      </Link>
                    </div>
                  </div>
                </article>
              );
            })}
          </div>
        )}
      </section>

      {/* ── Footer ──────────────────────────────────────── */}
      <footer className="newspaper-footer">
        <div className="newspaper-footer-accent" />
        <div className="newspaper-footer-content">
          <span className="newspaper-footer-brand">ChronicleAI</span>
          <span>Autonomous On-Chain Intelligence</span>
          <span className="masthead-dot">&bull;</span>
          <span>All content anchored on-chain via Chronicle Registry</span>
        </div>
        <div className="newspaper-footer-accent" />
      </footer>
    </div>
  );
}
