import type { ReactElement } from "react";
import { Link } from "react-router-dom";
import { EmptyState, LoadingState, RetryState } from "../../components/state-views.tsx";
import { StatusBadge, TimestampDisplay } from "../../components/data-primitives.tsx";
import { useAlerts } from "../alerts/use-alerts.ts";
import { useLatestDigest } from "../digests/use-latest-digest.ts";
import { usePremiumTeasers } from "../premium/use-premium.ts";

interface PublicationItem {
  id: string;
  type: "digest" | "alert" | "premium";
  title: string;
  summary: string;
  date: string;
  status: string;
  href: string;
  meta: Record<string, string>;
}

export function PublicationsPage(): ReactElement {
  const { alerts, isLoading: alertsLoading, error: alertsError, refetch: refetchAlerts } = useAlerts(100);
  const { state: digestState } = useLatestDigest();
  const { items: premiumItems, isLoading: premiumLoading } = usePremiumTeasers();

  const publications: PublicationItem[] = [];

  if (digestState.status === "success") {
    publications.push({
      id: digestState.data.id,
      type: "digest",
      title: digestState.data.title,
      summary: digestState.data.summary.slice(0, 200),
      date: digestState.data.publishedAt ?? digestState.data.reportDate,
      status: digestState.data.publicationStatus,
      href: "/digests/latest",
      meta: {
        ...(digestState.data.registryTxHash ? { "Registry Tx": digestState.data.registryTxHash } : {}),
      },
    });
  }

  for (const alert of alerts) {
    publications.push({
      id: alert.id,
      type: "alert",
      title: alert.title,
      summary: alert.summary,
      date: alert.publishedAt ?? new Date().toISOString(),
      status: alert.deliveryStatus,
      href: "/alerts",
      meta: {
        ...(alert.generationProvider ? { "Generated by": alert.generationProvider } : {}),
        ...(alert.confidence ? { Confidence: alert.confidence } : {}),
      },
    });
  }

  for (const item of premiumItems) {
    publications.push({
      id: item.id,
      type: "premium",
      title: item.title,
      summary: item.summaryPublic,
      date: "",
      status: "available",
      href: "/premium",
      meta: {
        Price: `${item.priceAmount} ${item.priceCurrency}`,
      },
    });
  }

  publications.sort((a, b) => {
    if (!a.date && !b.date) return 0;
    if (!a.date) return 1;
    if (!b.date) return -1;
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });

  const isLoading = alertsLoading || digestState.status === "loading" || premiumLoading;
  const hasError = alertsError || digestState.status === "error";

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <header className="text-center py-12 mb-8 border-b border-border/20">
        <h1 className="text-4xl font-bold tracking-tight text-foreground mb-3" style={{ fontFamily: "var(--font-space-grotesk)" }}>
          Publications Archive
        </h1>
        <p className="text-muted-foreground text-base max-w-2xl mx-auto">
          The complete archive of ChronicleAI intelligence bulletins — public alerts, digests, and premium analysis.
        </p>
      </header>

      {/* Navigation Filter Bar */}
      <nav className="flex items-center gap-2 mb-8 p-3 bg-muted/20 border border-border rounded-2xl flex-wrap">
        <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider px-2">Sections:</span>
        <span className="px-3.5 py-1.5 bg-accent/20 text-accent font-semibold text-sm rounded-xl">All Publications</span>
        <Link to="/digests/latest" className="px-3.5 py-1.5 text-muted-foreground hover:text-foreground text-sm font-medium transition-colors rounded-xl hover:bg-muted/30">Digest</Link>
        <Link to="/alerts" className="px-3.5 py-1.5 text-muted-foreground hover:text-foreground text-sm font-medium transition-colors rounded-xl hover:bg-muted/30">Alerts</Link>
        <Link to="/premium" className="px-3.5 py-1.5 text-muted-foreground hover:text-foreground text-sm font-medium transition-colors rounded-xl hover:bg-muted/30">Premium</Link>
      </nav>

      {/* Publications Timeline */}
      <section className="mb-12">
        {isLoading ? (
          <LoadingState message="Loading publications..." />
        ) : hasError ? (
          <RetryState title="Failed to load publications" message={alertsError ?? "Unknown error"} onRetry={refetchAlerts} />
        ) : publications.length === 0 ? (
          <EmptyState
            title="No publications yet"
            description="ChronicleAI content will appear here once alerts, digests, and premium items are published."
          />
        ) : (
          <div className="flex flex-col gap-0">
            {publications.map((pub) => {
              const typeColor = pub.type === "digest" ? "var(--accent)" : pub.type === "alert" ? "#f59e0b" : "#22c55e";
              const typeBorderColor = pub.type === "digest" ? "rgba(168,217,70,0.3)" : pub.type === "alert" ? "rgba(245,158,11,0.3)" : "rgba(34,197,94,0.3)";
              const typeBgColor = pub.type === "digest" ? "rgba(168,217,70,0.08)" : pub.type === "alert" ? "rgba(245,158,11,0.08)" : "rgba(34,197,94,0.08)";

              return (
                <article key={`${pub.type}-${pub.id}`} className="flex gap-6">
                  <div className="flex flex-col items-center w-5 flex-shrink-0 pt-6">
                    <div 
                      className="w-3.5 h-3.5 rounded-full flex-shrink-0 shadow-sm" 
                      style={{ background: typeColor }} 
                    />
                    <div className="w-[1px] flex-1 bg-border/40 mt-2" />
                  </div>
                  
                  <div className="flex-1 bg-frame border border-border rounded-2xl p-5 mb-5 hover:border-accent/40 transition-all duration-300 shadow-xs hover:shadow-md">
                    <div className="flex justify-between items-center mb-3 flex-wrap gap-2">
                      <span 
                        className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold border"
                        style={{ color: typeColor, borderColor: typeBorderColor, background: typeBgColor }}
                      >
                        <span className="w-1.5 h-1.5 rounded-full" style={{ background: typeColor }} />
                        {pub.type.charAt(0).toUpperCase() + pub.type.slice(1)}
                      </span>
                      <div className="flex items-center gap-3">
                        {pub.date && <TimestampDisplay timestamp={pub.date} />}
                        {pub.status !== "available" && (
                          <StatusBadge label={pub.status} variant={pub.status === "published" ? "success" : pub.status === "partial_failure" ? "warning" : "default"} />
                        )}
                      </div>
                    </div>
                    
                    <h3 className="text-lg font-semibold text-foreground mb-2 leading-snug">{pub.title}</h3>
                    <p className="text-muted-foreground text-sm leading-relaxed mb-4">{pub.summary}</p>
                    
                    <div className="flex justify-between items-center flex-wrap gap-3 pt-4 border-t border-border/10">
                      <div className="flex flex-wrap gap-2">
                        {Object.entries(pub.meta).map(([key, value]) => (
                          <span key={key} className="text-[11px] font-mono text-muted-foreground bg-muted px-2 py-0.5 rounded-lg border border-border/40">
                            {key}: {value.length > 30 ? `${value.slice(0, 16)}...` : value}
                          </span>
                        ))}
                      </div>
                      <Link to={pub.href} className="text-accent text-xs font-semibold hover:underline">
                        Read More &rarr;
                      </Link>
                    </div>
                  </div>
                </article>
              );
            })}
          </div>
        )}
      </section>
    </div>
  );
}
