import type { PublicAlertResponse } from "@chronicleai/schemas";
import type React from "react";
import {
  SourceReference,
  StatusBadge,
  TimestampDisplay,
} from "../../components/data-primitives.tsx";

interface AlertCardProps {
  alert: PublicAlertResponse;
  "data-testid"?: string;
}

function getConfidenceVariant(
  confidence?: string,
): "default" | "success" | "warning" | "error" | "info" {
  switch (confidence) {
    case "high":
      return "success";
    case "medium":
      return "warning";
    case "low":
      return "error";
    default:
      return "default";
  }
}

function getStatusVariant(status: string): "default" | "success" | "warning" | "error" | "info" {
  switch (status) {
    case "published":
      return "success";
    case "queued":
      return "info";
    case "failed":
      return "error";
    case "partial_failure":
      return "warning";
    default:
      return "default";
  }
}

export function AlertCard({
  alert,
  "data-testid": dataTestId = "alert-card",
}: AlertCardProps): React.ReactElement {
  return (
    <div 
      className="bg-frame border border-border rounded-2xl p-6 hover:border-accent/40 transition-all duration-300 shadow-xs hover:shadow-md"
      data-testid={dataTestId}
    >
      <div className="flex justify-between items-start mb-4 gap-4">
        <h3 className="text-xl font-semibold text-foreground leading-snug">
          {alert.title}
        </h3>
        <div className="flex gap-2 flex-shrink-0">
          {alert.confidence ? (
            <StatusBadge
              label={`${alert.confidence} confidence`}
              variant={getConfidenceVariant(alert.confidence)}
            />
          ) : null}
          <StatusBadge
            label={alert.deliveryStatus}
            variant={getStatusVariant(alert.deliveryStatus)}
          />
        </div>
      </div>

      <p className="text-muted-foreground text-sm leading-relaxed mb-4">
        {alert.summary}
      </p>

      <div className="flex flex-wrap gap-4 items-center text-xs text-muted-foreground border-t border-border/20 pt-4">
        {alert.publishedAt ? (
          <TimestampDisplay timestamp={alert.publishedAt} data-testid="alert-timestamp" />
        ) : null}

        {alert.generationProvider ? (
          <span className="flex items-center gap-1">
            Generated by:{" "}
            <code className="font-mono bg-muted px-1.5 py-0.5 rounded text-foreground">{alert.generationProvider}</code>
          </span>
        ) : null}

        {alert.sourceReferences?.length > 0 ? (
          <div className="flex gap-2 flex-wrap items-center min-[850px]:ml-auto">
            {alert.sourceReferences.map((ref, i) => (
              <SourceReference
                key={i}
                label="Source"
                reference={ref}
                data-testid={`source-ref-${i}`}
              />
            ))}
          </div>
        ) : null}
      </div>
    </div>
  );
}
