// Public alert card component

import type React from "react";
import type { PublicAlertResponse } from "@chronicleai/schemas";
import { StatusBadge, SourceReference, TimestampDisplay } from "../../components/data-primitives.tsx";

interface AlertCardProps {
  alert: PublicAlertResponse;
  "data-testid"?: string;
}

function getConfidenceVariant(confidence?: string): "default" | "success" | "warning" | "error" | "info" {
  switch (confidence) {
    case "high":
      return "success";
    case "medium":
      return "warning";
    case "low":
      return "error";
    default:
      return "default";
  }
}

function getStatusVariant(status: string): "default" | "success" | "warning" | "error" | "info" {
  switch (status) {
    case "published":
      return "success";
    case "queued":
      return "info";
    case "failed":
      return "error";
    case "partial_failure":
      return "warning";
    default:
      return "default";
  }
}

export function AlertCard({
  alert,
  "data-testid": dataTestId = "alert-card",
}: AlertCardProps): React.ReactElement {
  return (
    <div className="card" data-testid={dataTestId}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          marginBottom: "0.75rem",
          gap: "1rem",
        }}
      >
        <h3
          style={{
            fontSize: "var(--font-size-lg)",
            fontWeight: 600,
            color: "var(--fg-primary)",
            lineHeight: 1.3,
          }}
        >
          {alert.title}
        </h3>
        <div style={{ display: "flex", gap: "0.5rem", flexShrink: 0 }}>
          {alert.confidence ? (
            <StatusBadge
              label={`${alert.confidence} confidence`}
              variant={getConfidenceVariant(alert.confidence)}
            />
          ) : null}
          <StatusBadge
            label={alert.deliveryStatus}
            variant={getStatusVariant(alert.deliveryStatus)}
          />
        </div>
      </div>

      <p
        style={{
          fontSize: "var(--font-size-sm)",
          color: "var(--fg-secondary)",
          lineHeight: 1.6,
          marginBottom: "1rem",
        }}
      >
        {alert.summary}
      </p>

      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: "1rem",
          alignItems: "center",
          fontSize: "var(--font-size-xs)",
        }}
      >
        {alert.publishedAt ? (
          <TimestampDisplay timestamp={alert.publishedAt} data-testid="alert-timestamp" />
        ) : null}

        {alert.generationProvider ? (
          <span className="text-tertiary">
            Generated by: <code style={{ fontFamily: "var(--font-mono)" }}>{alert.generationProvider}</code>
          </span>
        ) : null}

        {alert.sourceReferences?.length > 0 ? (
          <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
            {alert.sourceReferences.map((ref, i) => (
              <SourceReference
                key={i}
                label="Source"
                reference={ref}
                data-testid={`source-ref-${i}`}
              />
            ))}
          </div>
        ) : null}
      </div>
    </div>
  );
}
