import type { PublicAlertResponse } from "@chronicleai/schemas";
import type React from "react";
import { Link } from "react-router-dom";
import {
  SourceReference,
  StatusBadge,
  TimestampDisplay,
} from "../../components/data-primitives.tsx";
import { PublicationProof } from "../../components/publication-proof.tsx";

interface AlertCardProps {
  alert: PublicAlertResponse;
  /** When false, renders as a plain card (e.g. already on the detail page). Default true. */
  linkable?: boolean;
  "data-testid"?: string;
}

const CHAIN_LABELS: Record<number, string> = {
  1: "Ethereum",
  8453: "Base",
  84532: "Base Sepolia",
  11155111: "Sepolia",
};

function getConfidenceVariant(
  confidence?: string,
): "default" | "success" | "warning" | "error" | "info" {
  switch (confidence) {
    case "high":
      return "success";
    case "medium":
      return "warning";
    case "low":
      return "error";
    default:
      return "default";
  }
}

function getStatusVariant(status: string): "default" | "success" | "warning" | "error" | "info" {
  switch (status) {
    case "published":
      return "success";
    case "queued":
      return "info";
    case "failed":
      return "error";
    case "partial_failure":
      return "warning";
    default:
      return "default";
  }
}

function formatEventType(eventType?: string): string | null {
  if (!eventType) return null;
  return eventType
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function AlertCard({
  alert,
  linkable = true,
  "data-testid": dataTestId = "alert-card",
}: AlertCardProps): React.ReactElement {
  const eventLabel = formatEventType(alert.eventType);
  const chainLabel =
    typeof alert.chainId === "number"
      ? (CHAIN_LABELS[alert.chainId] ?? `Chain ${alert.chainId}`)
      : null;

  const content = (
    <>
      <div className="flex justify-between items-start mb-4 gap-4">
        <h3 className="text-xl font-semibold text-foreground leading-snug">
          {alert.title}
        </h3>
        <div className="flex gap-2 flex-shrink-0 flex-wrap justify-end">
          {alert.confidence ? (
            <StatusBadge
              label={`${alert.confidence} confidence`}
              variant={getConfidenceVariant(alert.confidence)}
            />
          ) : null}
          <StatusBadge
            label={alert.deliveryStatus}
            variant={getStatusVariant(alert.deliveryStatus)}
          />
        </div>
      </div>

      <p className="text-muted-foreground text-sm leading-relaxed mb-4">
        {alert.summary}
      </p>

      {(eventLabel || chainLabel || alert.protocol) && (
        <div className="flex flex-wrap gap-2 mb-4">
          {eventLabel ? (
            <span className="text-[11px] font-medium px-2 py-0.5 rounded-lg bg-muted border border-border/40 text-muted-foreground">
              {eventLabel}
            </span>
          ) : null}
          {chainLabel ? (
            <span className="text-[11px] font-medium px-2 py-0.5 rounded-lg bg-muted border border-border/40 text-muted-foreground">
              {chainLabel}
            </span>
          ) : null}
          {alert.protocol ? (
            <span className="text-[11px] font-medium px-2 py-0.5 rounded-lg bg-muted border border-border/40 text-muted-foreground">
              {alert.protocol}
            </span>
          ) : null}
        </div>
      )}

      <PublicationProof
        registryTxHash={alert.registryTxHash}
        contentHash={alert.contentHash}
        sourceEventHash={alert.sourceEventHash}
        gasUsed={alert.gasUsed}
        gasUsedWei={alert.gasUsedWei}
        keeperHubRunId={alert.keeperHubRunId}
        explorerUrl={alert.explorerUrl}
        compact={linkable}
        data-testid="alert-publication-proof"
      />

      <div className="flex flex-wrap gap-4 items-center text-xs text-muted-foreground border-t border-border/20 pt-4 mt-4">
        {alert.publishedAt ? (
          <TimestampDisplay timestamp={alert.publishedAt} data-testid="alert-timestamp" />
        ) : null}

        {alert.generationProvider ? (
          <span className="flex items-center gap-1">
            Generated by:{" "}
            <code className="font-mono bg-muted px-1.5 py-0.5 rounded text-foreground">
              {alert.generationProvider}
            </code>
          </span>
        ) : null}

        {alert.sourceReferences?.length > 0 ? (
          <div className="flex gap-2 flex-wrap items-center min-[850px]:ml-auto">
            {alert.sourceReferences.map((ref, i) => (
              <SourceReference
                key={i}
                label="Source"
                reference={ref}
                data-testid={`source-ref-${i}`}
              />
            ))}
          </div>
        ) : null}
      </div>
    </>
  );

  const className =
    "block bg-frame border border-border rounded-2xl p-6 hover:border-accent/40 transition-all duration-300 shadow-xs hover:shadow-md";

  if (linkable) {
    return (
      <Link to={`/alerts/${alert.id}`} className={className} data-testid={dataTestId}>
        {content}
      </Link>
    );
  }

  return (
    <div className={className} data-testid={dataTestId}>
      {content}
    </div>
  );
}
